### ISSUE TITLE
BPM Supreme dont work.

### ISSUE THREAD

**Issue by djpd** [Esgrove/recordpool-dl#36]
BPMSupreme not work, im think the page WWW changed in python file is https://app.bpmsupreme.com/new-releases/classic/audio and redirect to https://app.bpmsupreme.com/d (old page too dont work).  Now old page is https://classic.bpmsupreme.com/new-releases/smart/audio  or https://classic.bpmsupreme.com/new-releases/audio/genre/dance Can you try fix this? ;-) Thanks bro 

Here is error:

`
RECORDPOOL DL
Starting ChromeDriver...

DevTools listening on ws://127.0.0.1:64472/devtools/browser/78ff3161-884c-4fac-a164-7d19eca527c1

pool: BPMSupreme
path: D:\Dropbox\DJ MUSIC SORT\BPMSUPREME
disk: 206.5 GB (44.3%) free
Choose genres manually and press a key to continue...

Choose mode:
 0: Single page
>0: Multiple pages
0

ERROR: <class 'selenium.common.exceptions.TimeoutException'>
Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x011C1C53+49427]
        (No symbol) [0x01155F41]
        (No symbol) [0x0105C64D]
        (No symbol) [0x01089818]
        (No symbol) [0x010898DB]
        (No symbol) [0x010B87D2]
        (No symbol) [0x010A4A64]
        (No symbol) [0x010B6F2A]
        (No symbol) [0x010A4816]
        (No symbol) [0x01081127]
        (No symbol) [0x010822AD]
        GetHandleVerifier [0x01417149+2496009]
        GetHandleVerifier [0x0145D572+2783794]
        GetHandleVerifier [0x01457491+2758993]
        GetHandleVerifier [0x012411D0+571024]
        (No symbol) [0x0115F96A]
        (No symbol) [0x0115BD88]
        (No symbol) [0x0115BE6B]
        (No symbol) [0x0114EA97]
        BaseThreadInitThunk [0x76EBFA29+25]
        RtlGetAppContainerNamedObjectPath [0x77DB7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77DB7A6E+238]

  File "C:\Users\pd\Downloads\recordpool-dl-main\src\RecordPoolDownloader.py", line 163, in <module>
    downloader.run_loop()

  File "C:\Users\pd\Downloads\recordpool-dl-main\src\RecordPoolDownloader.py", line 52, in run_loop
    self.single_page_loop()

  File "C:\Users\pd\Downloads\recordpool-dl-main\src\RecordPoolDownloader.py", line 58, in single_page_loop
    self.pool.update_current_page()

  File "C:\Users\pd\Downloads\recordpool-dl-main\src\RecordPool.py", line 175, in update_current_page
    self.current_page_number = self.get_page_number()
                               ^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\pd\Downloads\recordpool-dl-main\src\BPMSupreme.py", line 47, in get_page_number
    WebDriverWait(self.driver, self.wait_time).until(

  File "C:\Users\pd\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)

--------------------
BPMSupreme
Total files downloaded: 0 / 0.0 MB

Press any key to continue . . .`

**Comment by Esgrove** [comment]
I am no longer supporting this project, and I don't use bpmsupreme anymore either so I could not fix it in anycase.
